### PR TITLE
Update NonceGenerator.cs

### PR DESCRIPTION
**Pull request by lennybacon**
Better performance, less memory allocation

### CODE REVIEW

**Comment by BadriL** [comment]
Creating an instance of `RNGCryptoServiceProvider` does not take time. What takes time is the call to `GetBytes`. So, I don't see a whole lot of difference in having a static instance vs creating it every time. In order to have it static, `RNGCryptoServiceProvider` must be thread-safe and it is right now. But then, I'd prefer not to deal with thread contentions at all, unless there is a strong incentive to do so. If you have any references that point towards keeping a static instance for better performance, lesser memory foot print, etc, please let me know. At this point, I'd prefer to keep it the way it is.

**Comment by lennybacon** [comment]
I'll let numbers speak. I wrote a small example: Run 10 times, each separated by GC.WaitForFullGCComplete(1000), call GetBytes() 10,000 times

untitled

It's up to you...

**Comment by BadriL** [comment]
Fair enough.

@leastprivilege This PR was created before my PR was merged. So, there will be conflicts. Should @lennybacon create a fresh PR or you will be able to resolve the conflict and merge? Basically, the only change is that `RNGCryptoServiceProvider` will be a static instance instead of getting newed up every time `Generate` is called.

**Comment by leastprivilege** [comment]
somebody has to send me a PR ;)

**Comment by lennybacon** [comment]
I'll create a new PR!

**Pull request closed without merging**
